### ISSUE TITLE
(Emacs) File is missing: Cannot open load file, No such file or directory, memoize

### ISSUE THREAD

**Issue by soldm** [domtronn/all-the-icons.el#118]
I installed the **NeoTree** plugin into `~/.emacs.d/plugins/` folder, and wrote a path
```el
(add-to-list 'load-path "~/.emacs.d/plugins/neotree/")
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)
```
into `~/.emacs` file. This plugin is worked. ✔️

---

After when i installed the **All the Icons** plugin in `~/.emacs.d/plugins/` and wrote a path, the Emacs gives a error:

```bash
File is missing: Cannot open load file, No such file or directory, memoize
```
![screenshot from 2018-07-03 23-50-10](https://user-images.githubusercontent.com/38924019/42245112-3cfa03f0-7f20-11e8-8c6f-aeb5ad3a3f26.png)

---

**Structure of** `~/.emacs.d`

```
.emacs.d/
    themes/
    plugins/
        neotree/
            neotree.el
            ...
        all-the-icons/
            all-the-icons.el
            ...
```

---

**Tried:**

```el
(use-package all-the-icons)
```
❌  

```el
(add-to-list 'load-path (expand-file-name "~/.emacs.d/plugins/all-the-icons"))
```
❌  

```el
(load-file "~/.emacs.d/plugins/all-the-icons/all-the-icons.el")
```
❌  

---
**Info:**
**~Fedora** 28
**~Emacs** 26.1

**Comment by arvinddeshraj** [comment]
I'm also using Fedora 28 and Emacs 26.1 and faced a similar issue.
The issue is Emacs is unable to find the memoize package.

Installing the memoize package resolved the problem for me.
You can download the package from the MELPA stable repository

Evaluate this in your scratch buffer:
```elisp
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

Then refresh the package contents and install memoize-
1. M-x package-refresh-contents
2. M-x package-install RET memoize RET


Please keep in mind that I'm new to Emacs and I'm not sure if this is the right way to solve the issue. 
This is just what worked for me.

**Comment by wyuenho** [comment]
all-the-icons requires memoize to work. Please install that package first before requiring all-the-icons.
