### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#19]
I execute code:

``` elisp
(all-the-icons-oction "git-branch")
```

This caused Emacs segment fault.

**Comment by domtronn** [comment]
This works fine for me... See the attached screen shot.

<img width="712" alt="screen shot 2016-09-27 at 08 36 28" src="https://cloud.githubusercontent.com/assets/5881414/18864323/b24dd90e-848d-11e6-9f37-7858361a87e1.png">

I did notice however, that you spelt the function incorrectly, _i.e._ `oction` instead of `octicon` - Of course, this could be just when typing up this issue? But could you please check again by calling

```elisp
(all-the-icons-octicon "git-branch")
```

If you're still getting this problem, have you installed all of icon sets correctly?

**Comment by stardiviner** [comment]
Yes, it's typo. I use code completion. Maybe because icon sets install wrong. I will try again to install them correctly. When I execute your code, noticed that the CPU becomes high, and a few seconds later, Emacs segmant failed.

**Comment by stardiviner** [comment]
And I tried `emacs -q`. It works fine. It should be my init files config problem. I will dive into. Update info later.

**Comment by domtronn** [comment]
Are you running Emacs in a windowed application _(i.e. `window-system` not `nil`)_ or are you running it in a terminal?

**Comment by stardiviner** [comment]
I launch Emacs from `tmux`.

**Comment by domtronn** [comment]
I _maybe_ noticed a similar thing when I was developing my _custom_ font... It seemed to be to do with conflicting unicode characters _(for certain brackets of unicode characters)_ - However, all of the fonts included with this package work together were tested by printing _all_ the icons this package supports using

```elisp
(all-the-icons-insert-icons-for "alltheicon")
(all-the-icons-insert-icons-for "octicons")
(all-the-icons-insert-icons-for "fileicon")
(all-the-icons-insert-icons-for "faicon")
(all-the-icons-insert-icons-for "wicon")
```

Sooo, the only thing I could think of would be the installation of the font? Or if you have lots of other symbol fonts that could maybe conflict it?

**Comment by stardiviner** [comment]
Yes, I have other symbol fonts. How to debug this conflict issue?

**Comment by domtronn** [comment]
Have you tried reinstalling the fonts? And is this issue still happening? Because I'd like to know if that fixes it first.

If it's still happening, trying _uninstalling_ the Octicon font set and try inserting the `git-branch` icon again _(or its unicode character `\xf020` i.e. `(insert "\xf020")`)_ and see if this _still_ causes your segmentation fault.

If it doesn't, then that would suggest that maybe the Octicon fontset has a conflict - It might also insert the icon/symbol of the font that it was conflicting with.

Sorry, I'm far from familiar with debugging this kind of issue and a lot of these suggestions are just educated guesses...

**Comment by domtronn** [comment]
Also, maybe you could tell me the other Symbol fonts you have installed and I could then try and reproduce the problem?

**Comment by stardiviner** [comment]
@domtronn I installed many fonts, I don't know which symbol fonts are. To reproduce for you is a difficult problem.

**Comment by stardiviner** [comment]
I have tested with and without `all-the-icons` fonts folder all fonts. by running command `fc-cache -f` to update fonts.
And also tested with `emacs -q` and `(require 'all-the-icons)`.
They works.

So the problem must in my other packages or my init files.
I will bisect my init files later. Update here as soon as possible.
Thanks for your help.

**Comment by domtronn** [comment]
Sorry I couldn't be of more help! I hope you're able to fix it soon.

 If you are able to figure out what the problem is - Whether that's a conflicting package or some config in your init I would highly appreciate you letting me know what it is. Then I can add it to the Readme in case anyone else comes across the same problem :)

**Comment by stardiviner** [comment]
Ok, Just I don't have time to bisect my init files. I will update after I have result. Thanks for your patient.

**Comment by stardiviner** [comment]
After bisecting my init files:
Found reason:

```elisp
(set-fontset-font t 'unicode
                  (font-spec :name "Symbola") nil 'append)
```
