### ISSUE TITLE
installing icons always prompts for installation directory in terminal mode

### ISSUE THREAD

**Issue by salotz** [domtronn/all-the-icons.el#237]
I wanted to script the installation of the fonts from the shell but I'm running into an issue that the install function will always prompt you for the font installation when your in non-graphical mode.

I'm trying to run this:

```
emacs --eval '(all-the-icons-install-fonts t)' -nw --kill
```

But it prompts me "Font installation directory:" and stalls the script (I want to run the script without interaction).

If I run the same thing with the GUI it works fine:

```
emacs --eval '(all-the-icons-install-fonts t)' --kill
```

To me this is a bug, but also the argument to this command should be the path you want to install them to: `(all-the-icons-install-fonts "~/.local/share/fonts)`

**Comment by wyuenho** [comment]
Do you have a PR? This is a super low priority issue I'll likely not dedicate anytime to.

**Comment by salotz** [comment]
No, I would have linked it if I did.

**Comment by kkhan01** [comment]
Oh, I think I know why it does this! These [lines](https://github.com/domtronn/all-the-icons.el/blob/5fa728399bd6233a82bbfd4f7cb203a1d7ede708/all-the-icons.el#L997-L1005) use `window-system`, which is an issue for daemon users as well. A PR should change the casing to use the more logical variable `system-type` (which is set regardless of frames, but also, I think the os makes more sense to determine font location than the window system in general as well). 

Personally I'm using the [1 second logic described here](https://emacs.stackexchange.com/a/12352) since I also use `find-font`.

**Comment by salotz** [comment]
Just confirming that the fix works. I hadn't been able to test until now. Thanks a lot for that :) Now setup is completely automated.
