### ISSUE TITLE
Not working on neotree

### ISSUE THREAD

**Issue by eedahl** [domtronn/all-the-icons.el#25]
I can't get this to work with neotree. I've followed the instructions in [this video](https://www.youtube.com/watch?v=6airCRZqawM), but all I get are squares with hex numbers in them. I use Spacemacs.

**Comment by domtronn** [comment]
Hi there, have you installed the fonts provided with this package?

They can all be found [here](https://github.com/domtronn/all-the-icons.el/tree/master/fonts) and you want to download all the `.ttf` files and install them

**Comment by eedahl** [comment]
That solved it, thanks! I see now that it was mentioned under installation. Maybe a *NB* Install the fonts! is in order for people as sloppy as me, haha.

**Comment by domtronn** [comment]
Glad I could help! :)

And I've updated the ReadMe to put a bit more emphasis on the need to install the fonts, haha

**Comment by eedahl** [comment]
Nice! Btw, getting all-the-icons via Spacemacs, it didn't actually download the fonts, so maybe:

"they are available in the fonts directory, or below."

**Comment by domtronn** [comment]
Yeah the fonts aren't packaged as part of the Melpa release since their use is platform dependent, I couldn't do a font install during the package install, so it kinda has to be an exercise for the user.

But that's a good point, I can see how saying it's available in `fonts` suggests they would be downloaded as part of the package.

I may look into things like `brew` to install all of the fonts - but again that's an OSX only thing, so it wouldn't help Linux users 😛

**Comment by eedahl** [comment]
Yeah, I use Windows myself ^^

**Comment by veekram** [comment]
Yeah worked like a charm.
