### ISSUE TITLE
Broken dependency?

### ISSUE THREAD

**Issue by schvabodka-man** [domtronn/all-the-icons.el#32]
For some reason i can't install package from MELPA. When i'm trying to install it i get
`error: Package ‘font-lock+-0’ is unavailable
`
In fact that doesnt work with melpa-stable, with the regular melpa  everything is ok so i think there is something wrong with package in melpa-stable

**Comment by domtronn** [comment]
Yep, you're definitely right!

I've just had a look on both MELPA and MELPA Stable, and [MELPA](http://melpa.milkbox.net/#/font-lock%2B) has `font-lock+` in it, whereas MELPA Stable does not :(

It seems to be because there's never been a major version of the dependency... [`font-lock+`](https://www.emacswiki.org/emacs/font-lock%2B.el) is an emacs wiki snippet and the [MELPA recipe](https://github.com/melpa/melpa/blob/master/recipes/font-lock%2B) fetches it from there.

However the file says its still on [`Version: 0`](https://github.com/emacsmirror/emacswiki.org/blob/master/font-lock%2b.el#L9) and MELPA Stable only builds semantic versions _(probably greater than 0)_ so it won't pick it up as a stable build... 

I'll reach out to the maintainer and see if he can just bump the Version to `1.0.0`, this should trigger a Stable build and the dependency should then be there, hopefully.

Sorry I missed this! I'll keep you posted here. In the meantime, I guess you can install `font-lock+` from MELPA unstable...

**Comment by domtronn** [comment]
Although, I've just had a quick read of the [MELPA Documentation](https://github.com/melpa/melpa#recipe-format) and it suggests that fetching packages from Emacs Wiki _(which this on does)_ is deprecated. So I'm not confident that incrementing the version will work for Emacs Wiki packages they way tags work for Git packages.

They also [don't recommend the use of MELPA stable](https://github.com/melpa/melpa#melpa-stable)...

**Comment by domtronn** [comment]
Closing this as dependency is only missing when installing from MELPA stable which is discouraged from use. 

If anyone else comes across this, I will add something to the `README.md`

**Comment by Xiaoming-Zhao** [comment]
@domtronn 
Hi, sorry to interrupt. Actually now I use spacemacs and it use Melpa as default. However, I still met the same problem which states:
```
Cannot open load file: No such file or directory, font-lock+
```

Any suggestion?

**Comment by domtronn** [comment]
@Xiaoming-Zhao Have Did you install `all-the-icons` from Melpa or download it manually? I've tried recreating this myself by repeatedly deleting `font-lock+` and trying to reinstall it, either through [`use-package`'s `:ensure` functionality](https://github.com/jwiegley/use-package#for-packageel-users), or manually by calling `package-list-packages` and installing it from there...

The only difference I could see is that I call `package-initialize`

```el
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize nil)
```

This sets `package` up with all of the load paths needed to require in packages. So it could be that it's passing `font-lock` because it's native to Emacs and failing on `font-lock+` because it's not beed added to the load path?

**Comment by Xiaoming-Zhao** [comment]
@domtronn Thanks a lot for your kind reply.

I did the following:

1. I `M-x list-packages` and I found `font-lock+`. I installed it in that page

2. I went back to configure file and typed
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize nil)
(require 'font-lock+)
```
When I ran the configure, it showed
```
Package ‘font-lock+-20170101.947’ deleted.
```

3. Everything seemed right until now. However, when I opened a new emacs it just told me configure failed and I had to comment the `(require 'font-lock+)`.

I would really appreciate it if you could kindly give me some advice.

**Comment by Xiaoming-Zhao** [comment]
@domtronn  Hi, I just fixed this by copying the `font-lock+.el`  to a file from [here](https://github.com/emacsmirror/emacswiki.org/blob/master/font-lock%2b.el) and put it in the local. Then type the following:
```
(add-to-list 'load-path "/path/to/font-lock+.el")
(require 'font-lock+)
``` 

Thanks a lot for your patience!

**Comment by domtronn** [comment]
@Xiaoming-Zhao I'm glad you managed to get it working! That should work fine, I don't think `font-lock+` is actively maintained so it's very unlikely to change.

However, I'm still interested as to why `package.el` isn't adding `font-lock+` to your load path, it should do so automatically... If you comment out `(require 'font-lock+)` with `font-lock+` installed from melpa and then run

```el
C-h v load-path
;; or
M-: (describe-variable 'load-path)
```

It should list out all your packages' load paths, so you could search for `font-lock+` in that list to see if it's added the melpa one?

**Comment by Xiaoming-Zhao** [comment]
@domtronn Hi, sorry for the delay. I find that there is a `font-lock+-readme.txt` located at `/Users/apple/.emacs.d/elpa`. However, there does not exist any other `font-lock+` related files or directories.

**Comment by amosbird** [comment]
This https://github.com/melpa/melpa/pull/5008 completely make `font-lock+` unreachable.

**Comment by a13** [comment]
For those who use Quelpa there's a way to install it:

```
(use-package font-lock+
  :ensure t
  :quelpa
  (font-lock+ :repo "emacsmirror/font-lock-plus" :fetcher github))
```
