### ISSUE TITLE
icons not aligned 

### ISSUE THREAD

**Issue by untoreh** [domtronn/all-the-icons.el#33]
https://github.com/jaypei/emacs-neotree/issues/214

**Comment by domtronn** [comment]
This issue is hard to fix... We can propertize the height and vertical alignment of font characters, but the widths are pretty static and they can't be horizontally aligned like you would with CSS. 

This is part of the reason that I recommend having _tab_ characters between the icons and the file/directory names in NeoTree - Tabs at least fill whitespace and should cause monospace fonts to line up.

I could update `all-the-icons-icon-for-dir` to place a tab between the icon and the directory name which would look like the screenshot below...

<img width="724" alt="screen shot 2017-02-03 at 21 35 06" src="https://cloud.githubusercontent.com/assets/5881414/22609321/ab8d8d5e-ea58-11e6-8985-7f78b287c6a1.png">

But that's then dependent on the users tab width and things and it still puts quite a lot of padding between them. If you're happier with this appearance, I'll push these modifications?
