### ISSUE TITLE
Some icons not correctly display

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#44]
When I use code:
```elisp
(all-the-icons-icon-for-file (buffer-file-name) :v-adjust -0.05)
```
in my custom mode-line.

The icon is wrong, not the correct icon. For example, the elisp buffer should show the emacs icon, but it is not. Not just elisp icon, also including Org-mode icon, and clojure-mode icon etc.

Check out the screenshot.

![all-the-icons wrong icons](https://cloud.githubusercontent.com/assets/378699/23512177/b6f674c4-ff9a-11e6-826e-6fa8c44cb8b9.png)

BTW, seems I can't change the icon size. How to adjust the icon size by override args?

**Comment by domtronn** [comment]
Hi @stardiviner, could you send/link me to the mode line code that you're running?

Also, what happens if you run the following inside a `fundamental-mode` buffer?

```el
(insert (all-the-icons-icon-for-file "Code.org" :v-adjust -0.05))
```

Lastly, you can override the _size_ of the icon using the `:height` property, for example

```el
(all-the-icons-icon-for-file "Code.org" :height 2.0)
```

**Comment by stardiviner** [comment]
Here is the result I run:

![all-the-icons-mode-icon](https://cloud.githubusercontent.com/assets/378699/23982286/86669318-0a47-11e7-84b3-6da77f028422.png)

You can see that the first line code works fine. But the second line code which appears in echo-area is wrong.

I run in Emacs minimal init config.

**Comment by domtronn** [comment]
Hmm, this is strange. I wouldn't expect the minibuffer to render the icon as its not font locked correctly the way the rest of Emacs is. So the `fundamental-mode` buffer seems to work. I'll look at getting a linux box to run this in and see if I can reproduce it but this might take a while...

Do you have `font-lock+` installed? 

Also, what happens if you run the following?

```el
(setq-local mode-line-format '("%e" (:eval (all-the-icons-icon-for-file "Code.org" :height 2.0))))
```

The above works for me... So it'll be interesting to see if its the mode line rendering that's causing this!

**Comment by stardiviner** [comment]
Yes, I have `font-lock+` installed.
After running your code, it works as expected.

**Comment by stardiviner** [comment]
![all-the-icons-major-mode](https://cloud.githubusercontent.com/assets/378699/25033969/728e63a4-2115-11e7-8d86-cf69c13d01c3.png)
