### ISSUE TITLE
How to use this package with speedbar?

### ISSUE THREAD

**Issue by et2010** [domtronn/all-the-icons.el#45]
Thanks for this great package! It looks awesome with neotree and dired. I also use speedbar a lot so I'm curious if there is any way to make the two work together? I googled but there is barely any relevant information.

**Comment by domtronn** [comment]
**Speedbar**'s now part of Emacs core right? 
In which case, I'm not _100%_ sure how I can contribute changes to it... But, there might be something I can do with hooks or modifying functions? But it might be more of a patch on the **Speedbar** functionality rather than actual support.

I'll have a look into this when I get some free time and let you know what I found out 😃

**Comment by et2010** [comment]
That's great! thanks

**Comment by noxdafox** [comment]
This [link](https://emacs.stackexchange.com/questions/28703/how-to-replace-the-icons-in-speedbar) might be useful.

**Comment by et2010** [comment]
Thanks for your attention. Since I'm a happy user of imenu-list now, I'm closing this. Feel free to reopen it.

**Comment by jdek** [comment]
Not sure this should have been closed? Shouldn't this package be setting the `ezimage-directory-*` in order to work with speedbar?
