### ISSUE TITLE
Adding compilation mode

### ISSUE THREAD

**Issue by jwintz** [domtronn/all-the-icons.el#48]
Hello,

First of all, thanks for this awesome package.

I wanted to add an icon for `compilation-mode` that I use a lot, so I went into `all-the-icons.el` and added the following to the list `all-the-icons-mode-icon-alist`.

```lisp
        (compilation-mode all-the-icons-faicon "cogs" :height 1.0 :v-adjust 0.0)
```

However, I'm using all-the-icons in many places but I'm particularly interested in my modeline segment (using spaceline) which is defined as follows

```lisp
    (spaceline-define-segment prolusion-mode-icon
      (let ((icon (all-the-icons-icon-for-buffer)))
        (unless (symbolp icon)
          (propertize icon
                    'help-echo (format "Major-mode: `%s`" major-mode)
                    'display '(raise 0.0)
                    'face `(:height 0.9 :family ,(all-the-icons-icon-family-for-buffer) :inherit)))))
```

`all-the-icons-icon-for-buffer` doesn't provides me with `compilation-mode`. I guess it comes from ...

```lisp
        (if (and (buffer-file-name)
             (all-the-icons-auto-mode-match?))
```

... which is ...

```lisp
    (defun all-the-icons-auto-mode-match? (&optional file)
      "Whether or not FILE's `major-mode' match against its `auto-mode-alist'."
      (let* ((file (or file (buffer-file-name) (buffer-name)))
             (auto-mode (all-the-icons-match-to-alist file auto-mode-alist)))
        (eq major-mode auto-mode)))
```

... which is ...

```lisp
    (defun all-the-icons-match-to-alist (file alist)
      "Match FILE against an entry in ALIST using `string-match'."
      (cdr (--first (string-match (car it) file) alist)))
```

The point is, I do not see any fallback for the mode involving `all-the-icons-mode-icon-alist`.

Could you please point me to what I'm missing ?

**Comment by domtronn** [comment]
Hi There!

`compilation-mode` won't actually use the `auto-mode-match?` function, I use this as an indicator that the file name is in the auto major mode and to use the _filename/extension_ to decide on the icon. This way you can have two files, for example, 

* `foo.js`
* `bar.jsx`

that both use `js2-mode` but have different icons rather than just the `js2-mode` icon. However, if inside one of those buffers you turn it into `css-mode` the CSS icon will appear instead.

But the `*compilation*` buffer doesn't match against the `auto-mode-alist` _(not entirely sure why?)_ so it'll instead call [`all-the-icons-icon-for-buffer`](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L602-L613) which _does_ use `all-the-icons-mode-icon-alist` 😃 

I'm surprised it didn't work when you added it to the list though... 

Did you evaluate that definition after you added it? 
Is it part of the list when you call `describe-variable all-the-icons-mode-icon-alist`?
What about if you try calling

```el
(add-to-list 
  'all-the-icons-mode-icon-alist 
  '(compilation-mode all-the-icons-faicon "cogs" :height 1.0 :v-adjust 0.0))
```

Either way, I was going to add this to the package since you pointed it out, thanks!

**Comment by jwintz** [comment]
Hello,

Actually it didn't show up directly, but today in my professional workflow, I noticed the "cogs" icon while building a project in my compilation buffer. I don't why it was missing yesterday. So congratulations, your package is well written and easy to dig into.

What for now ? Do you want me to submit a PR or will you as you mentionned add it to the next release to propagate on Melpa ?

- ju

**Comment by jwintz** [comment]
Many thanks for your response. I realized, one day too late, that my addon actually _does_ work !

I'll submit a PR right away :-)
