### ISSUE TITLE
spaceline-ml-ati not work with dashboard mode

### ISSUE THREAD

**Issue by jilen** [domtronn/all-the-icons.el#52]
When combine [this](https://github.com/domtronn/all-the-icons.el/wiki/Spaceline) with [dashboard](https://github.com/rakanalh/emacs-dashboard),
Following error was raised,

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p #<buffer *dashboard*>)
  spaceline-ml-ati()
  eval((spaceline-ml-ati) nil)
  eval-expression((spaceline-ml-ati) nil)
  funcall-interactively(eval-expression (spaceline-ml-ati) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

```
When I resize the emacs window, everything is fine.

**Comment by domtronn** [comment]
Try using the following config rather than what I put in the Wiki?

```el
(use-package spaceline :after powerline)
(use-package spaceline-all-the-icons :after spaceline 
  :load-path "path/to/spaceline-all-the-icons"
  :config (setq-default mode-line-format '("%e" (:eval (spaceline-ml-ati)))))
```

This _should_ cause it to evaluate later?  A lot of people have had issues with the loading of the mode line config... And I'm not entirely sure why its happening. 😞 

I've also been rewriting all that code [here](https://github.com/domtronn/spaceline-all-the-icons.el) into a proper package, so keep an eye on that!

**Comment by domtronn** [comment]
Closing, please try [`spaceline-all-the-icons`](https://github.com/domtronn/spaceline-all-the-icons.el) and if you still have issues, raise one there 🙂
