### ISSUE TITLE
Git Gutter support

### ISSUE THREAD

**Issue by idoo** [domtronn/all-the-icons.el#53]
Does somebody tried overwrite default git gutter symbols?
Currently I'm using that `plus` symbol, but it looks ugly in my opinion
```
  (fringe-helper-define 'git-gutter-fr+-added nil
    "...XX..."
    "...XX..."
    "...XX..."
    "XXXXXXXX"
    "XXXXXXXX"
    "...XX..."
    "...XX..."
    "...XX...")

```

**Comment by domtronn** [comment]
I've had a brief look at this, and [`git-gutter-fringe`](https://github.com/syohex/emacs-git-gutter-fringe) isn't going to work... The `fringe-helper-define` macro declares an [XPM image](https://en.wikipedia.org/wiki/X_PixMap) rather than using actual characters so it's probably not going to be possible to swap it out, either for an icon or a normal `+`...

I _did_ get this working by just going back to [`git-gutter`](https://github.com/syohex/emacs-git-gutter) and setting

```el
(setq git-gutter:added-sign
      (propertize
       (all-the-icons-octicon "diff-added" :v-adjust 0)
       'face `( :family ,(all-the-icons-octicon-family)
                :height 0.8
                :foreground ,(face-foreground 'git-gutter:added)
                :inherit)))
```

But, I also had to modify [this](https://github.com/syohex/emacs-git-gutter/blob/master/git-gutter.el#L376-L385) function so that it didn't propertize the character itself and instead just inherited it from the set variable... Could _(hopefully)_ add some advice or a _theme_ that does all of this for you within the package.

Also, `git-gutter` now says that it [works with `linum-mode`](https://github.com/syohex/emacs-git-gutter#git-gutterel-vs-git-gutter-fringeel) _(Experimental)_! So maybe the fringe version isn't needed unless you want the symbols on the right hand side.

**Comment by idoo** [comment]
>  Could (hopefully) add some advice or a theme that does all of this for you within the package.

It will be awesome to store such changes in one place :)

**Comment by domtronn** [comment]
I've done a lot of research into this recently, and basically, some package _require_ you to define XPM images, which means you won't be able to swap them out for character icons.

The packages which _do_ allow you to uses characters would work with this package if you set it as a propertized string, but sometimes they override the `face` property making _some_ icons not render correctly 😞 

I've raised the PR above for `git-gutter` but yeah, it requires more integration with their packages than with `all-the-icons` itself.
