### ISSUE TITLE
icon for Reason?

### ISSUE THREAD

**Issue by anmonteiro** [domtronn/all-the-icons.el#76]
http://facebook.github.io/reason/

**Comment by domtronn** [comment]
Sure, I should be able to add this. It's available in the [latest version of `file-icons`](https://github.com/file-icons/source/blob/master/charmap.md#Reason) so I'll look at updating the version provided with this package 🙂 

Hopefully the unicode character mappings will be backwards compatible! Otherwise it'll be a huge breaking API change and people will need to reinstall fonts which could be a pain... I'll let you know how I get on

**Comment by anmonteiro** [comment]
Thanks. I don't think it's quite right.
`.ml` and `mli` files should be Ocaml files; Reason files end with `.re` or `.rei`

**Comment by domtronn** [comment]
Okay, no worries I'll update this.

I don't know much about OCaml & ReasonML and I couldn't see any documentation that mentioned the file extension - I basically searched for some ReasonML projects in GitHub and saw the files were `.ml` 😅

However, I have now found that the [FAQ](https://facebook.github.io/reason/faq.html) says that both `.ml`/`.mli` and `.re`/`.rei` are valid... So hopefully people are using the latter 👍

**Comment by anmonteiro** [comment]
That's great, thanks! 
I saw that `file-icons` also has an OCaml icon so it'd be great if we also supported those in `.ml`/`.mli` files :)

**Comment by domtronn** [comment]
Yep, I've added those in as well now 🙂

**Comment by anmonteiro** [comment]
Confirmed it's working. Looking great, thanks!
