### ISSUE TITLE
Elixir and Erlang icons

### ISSUE THREAD

**Issue by kwrooijen** [domtronn/all-the-icons.el#8]
The current fonts that we have don't support Elixir and Erlang. I found a font which does though:

LICENSE: MIT
https://github.com/fizzed/font-mfizz
http://fizzed.com/oss/font-mfizz

I don't know if you're interested in adding it though.

**Comment by domtronn** [comment]
I used to have *MFizz* included with these icons as well, but I think I removed it in favour of a combination of `file-icon` and `devicon` since they included erlang and elixir icons. Also, there was some weirdness with the positioning of the *MFizz* icons where they would appear underneath the resting icon line.. 

However, since #6 means I'll be removing `devicon` I will add these icons back in :) I'll probably add them to my custom Icon Set _(which is being updated as part of #6 anyway)_ since then I can maintain them myself

**Comment by kwrooijen** [comment]
All right, thanks for the work! I'll help however I can :)

**Comment by domtronn** [comment]
I've now added the Icons and file matchers for both Elixir and Erlang.

This will require you to install the `all-the-icons.ttf` font provided [here](https://github.com/domtronn/all-the-icons.el/tree/master/fonts/all-the-icons.ttf) which is just a replacement/rename of the previous `devicons.ttf`.

This _should_ actually fix #6... As I've now ported all the `devicon` icons into the `all-the-icons.ttf` font :)

**Comment by domtronn** [comment]
This has been resolved, see [this comment](https://github.com/domtronn/all-the-icons.el/issues/6#issuecomment-247769742) on Issue #6
