### ISSUE TITLE
Cannot load all-the-icons

### ISSUE THREAD

**Issue by ZucchiniY** [domtronn/all-the-icons.el#98]
I use this package by `(use-package all-the-icons :ensure t)` .
but now it doesn't work well while I start Emacs 25.3 on my Mac today
``` text
Error (use-package): Failed to install all-the-icons: Package ‘font-lock+-0’ is unavailable
Error (use-package): Cannot load all-the-icons
```

**Comment by preetpalS** [comment]
This is because **font-lock+** was removed from Melpa (https://github.com/melpa/melpa/pull/5008#issuecomment-360103510).

**Comment by Townk** [comment]
Even if I load font-lock+ locally this still happens. I have the following on my `init.el`:

```elisp
(use-package font-lock+
  :ensure nil
  :load-path "~/Projects/vendor/emacs/plugins/font-lock-plus/")

(use-package all-the-icons
  :after font-lock+)
```

And I still get:

```
Error (use-package): Failed to install all-the-icons: Package ‘font-lock+-0’ is unavailable
Error (use-package): Cannot load all-the-icons
```

**Comment by domtronn** [comment]
@Townk The problem is `use-package` doesn't add `font-lock+` to your load path which is what's used by the `require` call in the project to locate dependencies. _i.e._ you _have_ to have it installed using `package.el`

Unfortunately, this means that I'll have to remove the _explicit_ dependency on `font-lock+` - You can still load it before `all-the-icons` and the improvements it provides _should_ still work.

**Comment by Townk** [comment]
Are you saying the variable `load-path` does not contains the `font-lock-plus` directory? If I check the value of `load-path` after my init, I have this:

```
("~/Projects/vendor/emacs/plugins/targets/" "~/Projects/vendor/emacs/plugins/font-lock-plus/"
...)
```

**Comment by Townk** [comment]
Regardless, I updated all-the-icons to the latest version and my config file just works now.
